# <center> Numpy Basics </center>

In [2]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [3]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

a=np.array([1,2,3])

In [4]:
# print output
a


array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [5]:
#define a,b,c and d as instructed above

a=np.array([10])
b=np.array([1,2,3])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [8]:
#print dimentions of a,b, c and d

dima=np.ndim(a)
print(dima)
dimb=np.ndim(b)
print(dimb)
dimc=np.ndim(c)
print(dimc)
dimd=np.ndim(d)
print(dimd)



1
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [10]:
# print shape of each a,b ,c and d
shapea=np.shape(a)
shapeb=np.shape(b)
shapec=np.shape(c)
shaped=np.shape(d)

print(shapea)
print(shapeb)
print(shapec)
print(shaped)




(1,)
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [12]:
# print data type of c and d
type(c)
type(d)



numpy.ndarray

Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [14]:
#print type of a and b variable

type(a)
type(b)




numpy.ndarray

In [15]:
# Lets check length of array b, using len() function
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [17]:
# Define l1,l2,l3 and l4 as stated above.
# l1 =
# l2 =
# l3 =
# l4 =
l1=[10,20,30]
l2=[40,50,60]
l3=np.array(l1)
l4=np.array(l2)
l3


array([10, 20, 30])

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [23]:
#code here as instructed above
multipliction=[l1[i]*l2[i] for i in range(len(l1))]
multipliction
%timeit multipliction



23.8 ns ± 0.44 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [24]:
multipliction2=l3*l4
multipliction2


array([ 400, 1000, 1800])

Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [25]:
#Create a numpy array using arange with 1 and 11 as parameter in it


list=np.arange(1,11)
list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [26]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

array=np.arange(1,11,2)
array


array([1, 3, 5, 7, 9])

In [27]:
# create numpy array using eye function with 3 as passed parameter
array2=np.eye(3)
array2



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=
x=np.arange(1,17)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
# Reshape x with 2 rows and 8 columns
x=x.reshape(2,8)
x


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [30]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

x=x.reshape(2,4,2)
x


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [32]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

unknown=x.reshape(4,4)
unknown


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = x.reshape(2, 4, -1)


print (y)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [35]:
# Flattening y
y_flattened = y.flatten()
print(y_flattened)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [36]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)
a





array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [38]:
# Get third element in array a
third=a[2]


In [39]:
#Print 3rd, 5th, and 7th element in array a

third=a[2]
fifth=a[4]
seventh=a[6]
print(third,fifth,seventh)


6 10 14


Lets check the same for 2 D array

In [45]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# print the 3rd element from the 3rd row of a

third=a[2,2]
third

np.int64(9)

Well done!

Now lets check indexing for 3 D array

In [48]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b



array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

third=b[0,1,2]
third


np.int64(6)

In [50]:
# Create 1D array
arr=np.array([1,2,3,4,5,6,7,8,9])
arr



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# Slice elements from 1st to 5th element from the following array:
sliced=arr[0:5]
sliced




array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [52]:
# Slice elements from index 5 to the end of the array:

sliced=arr[5:]
sliced


array([6, 7, 8, 9])

In [53]:
# Slice elements from the beginning to index 5 (not included):
sliced=arr[:5]
sliced




array([1, 2, 3, 4, 5])

**STEP**

Use the step value to determine the step of the slicing:

In [54]:
# Print every other element from index 1 to index 7:

v=arr[1:7:2]
v


array([2, 4, 6])

Did you see? using step you were able to get alternate elements within specified index numbers.

In [55]:
# Return every other element from the entire array arr:


v=arr[::2]
v

array([1, 3, 5, 7, 9])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [56]:
# Print array a
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

sliced=a[2,1:5]
sliced


array([8, 9])

In [59]:
# In array 'a' print index 2 from all the elements :

v=a[0:3,2]
v


array([3, 6, 9])

In [60]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

sliced=a[:,1:]
sliced



array([[2, 3],
       [5, 6],
       [8, 9]])

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [61]:
x1=np.array([1,2,3,4,5])
x1



array([1, 2, 3, 4, 5])

In [64]:
# assign x2 = x1

x2=x1.copy()
x2

array([1, 2, 3, 4, 5])

In [65]:
#print x1 and x2

print("x1",x1)
print("x2",x2)


x1 [1 2 3 4 5]
x2 [1 2 3 4 5]


Ok now you have seen that both of them are same

In [67]:
# change 1st element of x2 as 10
x2[0]=10
x2

array([10,  2,  3,  4,  5])

In [68]:
#Again print x1 and x2
print("x1",x1)
print("x2",x2)



x1 [1 2 3 4 5]
x2 [10  2  3  4  5]


In [69]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))


False


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [70]:
# Create a view of x1 and store it in x3.
x3 = x1.view()
x3


array([1, 2, 3, 4, 5])

In [71]:
# Again check memory share between x1 and x3

print(np.shares_memory(x1, x3))


True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [72]:
#Change 1st element of x3=100

x3[0]=100

In [73]:
#print x1 and x3 to check if changes reflected in both

print("x1",x1)
print("x3",x3)


x1 [100   2   3   4   5]
x3 [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [74]:
# Now create an array x4 which is copy of x1

x4=x1.copy()
x4



array([100,   2,   3,   4,   5])

In [75]:
# Change the last element of x4 as 900

x4[4]=900
x4



array([100,   2,   3,   4, 900])

In [76]:
# print both x1 and x4 to check if changes reflected in both

print("x1",x1)
print("x4",x4)



x1 [100   2   3   4   5]
x4 [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [77]:
#Check memory share between x1 and x4


print(np.shares_memory(x1, x4))

False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [78]:
# stack x1 and x4 along columns.
np.hstack((x1,x4))


array([100,   2,   3,   4,   5, 100,   2,   3,   4, 900])

In [79]:
#stack x1 and x4 along rows
np.vstack((x1,x4))


array([[100,   2,   3,   4,   5],
       [100,   2,   3,   4, 900]])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [80]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

##join arr1 and arr2 along rows using concatenate() function
arr3=np.concatenate((arr1,arr2),axis=0)
arr3



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
##join arr1 and arr2 along columns using concatenate() function



## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [81]:
# append arr2 to arr1

np.append(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Lets use insert() function which Inserts values into array before specified index value

In [82]:
# Inserts values into array x1 before index 4 with elements of x4
np.insert(x1,4,x4)


array([100,   2,   3,   4, 100,   2,   3,   4, 900,   5])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [87]:
# delete 2nd element from array x2
x2
np.delete(x2,1)


array([10,  3,  4,  5])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!